apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: todo-service
  replicas: 1
  template:
    metadata:
      name: todo-service
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: coldstone.azurecr.io/todo-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: todo-service